name: UnionHG
main: eu.union.dev.HG
version: 1.0
commands:
  kit:
  feast:
  start:
  fly:
  build:
  info:
  score:
  ip:
  gamemode:
    aliases: [gm]
  admin:
  stats:
  ping:
  report:
  check:
  clearchat:
    aliases: [cc]
  inv:
  tp: